### PR TITLE
Upgrade version of cookie library

### PR DESCRIPTION
**Pull request by davidnaas**
Gives access to new cookie options

### CODE REVIEW

**Comment by nhoffmann** [comment]
LGTM 😄

**Comment by davidnaas** [comment]
> LGTM 😄

❤️

**Comment by ThisIsMissEm** [comment]
Nice to see y'all maintaining this — I have a fork of it too, it's just not really maintained

**Comment by davidnaas** [comment]
> Nice to see y'all maintaining this — I have a fork of it too, it's just not really maintained

Unfortunately it seems that the npm package is orphaned so I was unable to publish it with my account :(

**Comment by ThisIsMissEm** [comment]
Hrm. I'd suggest contacting the npm support team, as it is a module your organisation owns, they can probably restore access

**Pull request closed without merging**
